### ISSUE TITLE
Example in README not working?

### ISSUE THREAD

**Issue by JoshMcCullough** [samthor/scoped#14]
I cannot seem to get this to work (tried Firefox and Chrome), using the same example as in the README: https://jsfiddle.net/2urqv98y/1/

Thoughts?

**Comment by samthor** [comment]
Hmm, turns out this is probably [a security restriction](https://www.chromestatus.com/feature/5629709824032768#details) as the script is trying to do weird things to your style tags (a feature).

I'll update the README saying you need to inline the code / host it locally.

**Comment by samthor** [comment]
I've updated the README. Let me know if this solves your issue.

There's not really a good way to provide a warning aside in the README.

**Comment by JoshMcCullough** [comment]
Gotcha, I'll give it a try!
