### ISSUE TITLE
No CORS support

### ISSUE THREAD

**Issue by aandroyd** [samthor/scoped#2]
If the stylesheet is loaded with @import from another domain, Chrome 64+ hits a CORS error:
`Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules...`

**Comment by samthor** [comment]
I've just published 0.2.0 which makes this work. If we get a `SecurityError` reading/modifying imported CSS, we go and fetch it.

It's not perfect:
* it will create memory leaks (as it uses `URL.createObjectURL` and does not revoke them)
* it means loading CSS on page startup isn't synchronous (you might see a flash as CSS arrives later)
