### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by jcbhmr** [samthor/scoped#23]
I'm wondering if this project is still active in any fashion. I'd like to use this code myself. If this repo is active, I would love to open PRs for my changes (like TypeScript, more docs, readme upgrades, etc.). If it's archived, I'll just fork it and use it on my own.

[It looks like the answer is no](https://github.com/samthor/scoped/pulse/monthly), but I'd love to be wrong.

![](https://thum.io/get/https://github.com/samthor/scoped/pulse/monthly)

**Comment by samthor** [comment]
It does what it says on the tin. If you want to contribute PRs I'll happily accept them.

Look at [this issue](https://github.com/samthor/scoped/issues/15) for a short summary of the components.

**Comment by jcbhmr** [comment]
Sounds good! 👍 Thanks for the swift reply!
