### ISSUE TITLE
Clarify license owner

### ISSUE THREAD

**Issue by jcbhmr** [samthor/scoped#30]
![image](https://user-images.githubusercontent.com/61068799/218621466-748bc85f-45aa-4782-9a73-046e37a12869.png)

I assume this should be something like:

```
Copyright 2017 Sam Thorogood
```

I don't speak legal-ish, but I'd guess that you'd better make the change, not me.

**Comment by samthor** [comment]
Classically the LICENSE file in repos isn't changed, e.g., in my old life: https://github.com/GoogleChrome/web.dev/blob/main/LICENSE

It's just when you apply it to a file/header.

**Comment by jcbhmr** [comment]
Ah! Ok, I guess that kinda makes sense. It was just odd to see that the main LICENSE file didn't have a name attached to that copyright notice. Thanks for clearing that up!
